(function(){'use strict';
let snapshot,current,worker,page=0,category='lx',source='cloud',lot='xa',panel,baseline,inputDigest='',busy=false;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rate=x=>x===null||x===undefined?'—':(100*x).toFixed(1)+'%';const num=x=>x===null||x===undefined?'—':x.toFixed(2);
const names={xa:'新澳',la:'老澳',gc:'港彩'},cats={lx:'五连肖TOP20',z3:'三中三TOP20',te:'特码TOP20',exclude:'排除TOP20',experiment:'实验规律',rejected:'被淘汰规律',positions:'位置比较',pools:'5/6/8/12码池',quality:'数据与方法'};
function stat(s){return s?`${s.h}/${s.n}，${rate(s.rate)}；基准${rate(s.baseline)}，提升${num(s.pp)}百分点，${num(s.lift)}倍；均匀随机${rate(s.random)}`:'—';}
function row(r){const ready=r.status==='已验证规律'&&r.active&&r.forward?.n>=30&&r.forward?.p<=.0001;return `<article class="md-rule"><b>${esc(r.label)}</b><p><span>${r.type}</span> · ${r.status} · ${r.stability} · 来源：${r.source} · <b>未进入评分</b></p><p>结论：${esc(r.reason)}。训练收缩率 ${rate(r.train.shrunken)}；训练q=${num(r.trainQ)}，验证q=${num(r.validationQ)}。</p><div class="md-warning"><b>这一条现在对应什么：</b>${r.candidatePool.length?r.candidatePool.map(x=>typeof x==='number'?String(x).padStart(2,'0'):esc(x)).join('、'):'没有可直接转换的号码集合'}。${r.active?'当前条件已触发':'当前条件未触发，不应用'}。${r.status==='被淘汰规律'?'这条没有通过验证，不能据此推荐或排除。':'先看后续验证，不能当成必出或必杀。'}</div><p>简单看：发现时${r.train.h}/${r.train.n}次；换后面数据复查为${r.validation.h}/${r.validation.n}次，平常基准${rate(r.validation.baseline)}。不是只看一个高命中率。</p><details><summary>展开样本、基准与验证细节</summary><div class="md-scroll"><table><thead><tr><th>时间段</th><th>命中/样本、概率与基准</th></tr></thead><tbody><tr><td>发现集（前70%）</td><td>${stat(r.train)}</td></tr><tr><td>独立验证集（后30%）</td><td>${stat(r.validation)}</td></tr><tr><td>全历史（描述）</td><td>${stat(r.all)}</td></tr>${[100,50,30].map(w=>`<tr><td>最近${w}个有效转移</td><td>${stat(r.recent[w])}</td></tr>`).join('')}${r.walkForward.map((s,i)=>`<tr><td>前向验证段${i+1}：${s.from??'—'}～${s.to??'—'}</td><td>${stat(s)}</td></tr>`).join('')}<tr><td>冻结后新增期</td><td>${stat(r.forward)}</td></tr></tbody></table></div></details><button data-use-rule="${esc(r.id)}" ${ready?'':'disabled'}>应用通过验证的本期集合到筛选</button><small>独立验证、至少30个未来触发样本及前瞻检验均通过才开放；结构排除不能当作整肖/整池排除。</small><details><summary>实际用途与限制</summary><p>当前条件：${r.active?'触发':'未触发'}；关系涉及的号码/生肖集合：${r.candidatePool.map(esc).join('、')||'空集合'}。这只是实验关系的集合，验证失败时不能当作选号或硬排除建议。平均集合宽度${num(r.averagePoolSize)}。</p><p>非条件组对照率：训练${rate(r.train.comparison)}，验证${rate(r.validation.comparison)}。表中基准是同一时间段全部转移的无条件发生率。提升为条件率减去该基准；方向和显著性还需同时超过非条件组对照及均匀随机基准。</p></details></article>`;}
function render(){if(!panel||!current)return;const r=current,rs=new Map(r.rules.map(x=>[x.id,x]));let body='';
 if(category==='quality')body=`<h3>数据审计</h3><p>原始${r.quality.raw}条，有效${r.quality.rows.length}条；号码冲突${r.quality.conflicts.length}期，日期冲突${r.quality.dateConflicts.length}期。源数据只读，未删除或改写。</p><details open><summary>隔离/缺期问题</summary><pre>${esc(JSON.stringify(r.quality.issues,null,2))}</pre></details><details><summary>云端与文件快照差异</summary><p>号码冲突期：${r.quality.conflicts.join('、')||'无'}</p><pre>${esc(JSON.stringify(r.quality.dateConflicts,null,2))}</pre></details><h3>扩展窗口 walk-forward</h3><p>${r.walkForwardSelection.map(x=>`第${x.segment}段（${x.from}～${x.to}期），仅用此前${x.trainingTargets}个目标重新筛选：${x.selectedRules}条入选`).join("；")}</p><h3>统计协议</h3><p>先用至少29条历史预热；只配对连续期号。训练条件组及非条件组各至少30例，独立验证各至少12例。单一无条件关系允许直接与均匀抽取理论比较。两条件最多152个预先限定组合，不搜索三条件。每彩种全部合格检验统一BH，再用0.05/3控制三彩研究；Fisher双侧检验与保守的随机基准Chernoff界取较大p。小样本用20例非条件基准先验收缩，仅作描述，不改变检验。排名仅按训练证据。</p><p>冻结前70%发现集；后30%独立验证分成三个连续前向段。冻结后补录单独显示，不回填历史成绩。频率/遗漏仅用目标之前记录。相邻期检验并非因果证据。</p><ul>${r.limitations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>自动生成的特征</h3>${Object.entries(r.featureCatalog).map(([k,v])=>`<p>${esc(k)}：${esc(v)}</p>`).join('')}<p>人工规律完整保留在原栏目，未被此研究模块改写。人工规律是否有效需要逐条冻结定义后验证，不能自动归为A类。</p>`;
 else if(category==='positions')body=`<p>按训练证据比较正码①～⑥与特码；没有通过验证者时，不宣布哪个位置最有效。</p>${r.positions.map(x=>`<article class="md-rule"><b>${x.position}</b><p>${esc(rs.get(x.ruleId)?.label)}</p><p>训练q=${num(x.trainQ)}；验证${stat(x.validation)}；${esc(x.reason)}</p></article>`).join('')}`;
 else {let ids=category==='pools'?r.rules.filter(x=>x.id.includes('fixedpool:')).map(x=>x.id):r.tops[category]||[];let list=ids.map(id=>rs.get(id)).filter(Boolean);body=`<p>共${list.length}条，按训练证据排序。TOP表示待审查次序，绝不表示已验证；不凑足有效规律。</p>`+list.slice(page*5,page*5+5).map(row).join('')+`<div class="md-controls"><button data-page="${Math.max(0,page-1)}">上一页</button><span>${page+1}/${Math.max(1,Math.ceil(list.length/5))}</span><button data-page="${Math.min(Math.max(0,Math.ceil(list.length/5)-1),page+1)}">下一页</button></div>`;}
 panel.innerHTML=`<header><h2>机器自动发现规律报告 · ${names[lot]} · 10.1009.07</h2><button data-close>关闭</button></header><p class="md-warning">本轮已验证 ${r.validated} 条；机器规律全部未进入主评分。${r.validated?'通过者仍须未来期验证。':'当前没有证据支持据此硬排除或提高预测成绩。'}</p><div class="md-controls"><select id="md-lot">${Object.entries(names).map(([k,v])=>`<option value="${k}" ${lot===k?'selected':''}>${v}</option>`).join('')}</select><select id="md-source"><option value="cloud" ${source==='cloud'?'selected':''}>云端/当前页面</option><option value="file" ${source==='file'?'selected':''}>三份文件快照复算</option></select><button data-practice>直接看本期具体号码与组合</button><button data-refresh>用当前已录入数据重算</button><button data-download>下载完整报告JSON</button></div><p>来源：${esc(r.quality.source)}；指纹${r.quality.fingerprint}。最后实际记录第${r.split.finalPeriod}期。发现集${r.split.train}个转移（截至${r.split.trainEnd}期），独立验证${r.split.valid}个。枚举${r.enumerated.conditions}个条件、${r.enumerated.outcomes}个结果，达到门槛检验${r.enumerated.eligibleTests}次，训练通过${r.trainPassed}条。</p><nav>${Object.entries(cats).map(([k,v])=>`<button data-cat="${k}" class="${k===category?'selected':''}">${v}</button>`).join('')}</nav>${body}`;
 panel.querySelectorAll('[data-use-rule]').forEach(b=>b.onclick=()=>{const rule=current.rules.find(x=>x.id===b.dataset.useRule);if(window.ReferenceSystem&&rule)ReferenceSystem.applyMachine(rule,lot,current.split.finalPeriod);else alert('请从主分析系统打开并使用当前数据重算。');});panel.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;page=0;render();});panel.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=+b.dataset.page;render();});panel.querySelector('#md-lot').onchange=e=>{lot=e.target.value;select();};panel.querySelector('#md-source').onchange=e=>{source=e.target.value;select();};panel.querySelector('[data-practice]').onclick=()=>{if(window.PracticeSystem){panel.closest('dialog')?.close();PracticeSystem.show();}else window.location.href='index.html?v=10100907';};panel.querySelector('[data-close]').onclick=()=>panel.closest('dialog')?.close();panel.querySelector('[data-refresh]').onclick=recompute;panel.querySelector('[data-download]').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(current,null,2)],{type:'application/json'}));a.download='machine-discovery-'+lot+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
}
function select(){page=0;current=source==='file'?snapshot.fileSensitivity[lot]:snapshot.lots[lot];render();}
async function load(){snapshot=await fetch('machine-discovery-report.json?v=10100907',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('报告文件未发布');return r.json();});baseline=JSON.parse(JSON.stringify(snapshot));select();}
function recompute(){if(source==='file'){select();return;}let rows,maps,embedded;try{if(typeof DR==='undefined'||typeof CUR_LOT==='undefined')throw Error('请从主分析网站打开此报告，才能使用当前已同步记录');if(CUR_LOT!==lot)throw Error('请先在主网站切换到'+names[lot]+'，再打开报告重算');rows=DR.map(r=>({p:r.p,d:r.d,n:r.n.slice(),t:r.t}));maps={ZM,WX,WV};embedded=lot==='xa'?INIT_DR_XA:lot==='la'?INIT_DR_LA:INIT_DR_GC;}catch(e){alert(e.message);return;}
 inputDigest=JSON.stringify(rows);busy=true;if(worker)worker.terminate();worker=new Worker('discovery-worker.js?v=10100907');panel.innerHTML='<h2>正在后台重算…</h2><p>分析使用当前已录入开奖记录，不按当天日期虚构开奖。主评分保持不变。</p>';worker.onmessage=e=>{busy=false;if(e.data.error){panel.innerHTML='<p>重算失败：'+esc(e.data.error)+'</p>';return;}current=e.data.result;snapshot.lots[lot]=current;render();};worker.onerror=e=>{busy=false;panel.innerHTML='<p>后台分析加载失败：'+esc(e.message)+'。请刷新或查看已发布快照。</p>';};worker.postMessage({input:{rows,embeddedRows:embedded,source:'当前页面已录入并同步记录（独立只读研究）',trainingEndPeriod:baseline.lots[lot].split.trainEnd,historicalEndPeriod:baseline.lots[lot].split.finalPeriod},maps});
}
const style=document.createElement('style');style.textContent='.md-panel{font:14px/1.6 system-ui,sans-serif;color:#172435;background:#f5f7fb;padding:16px;max-width:1100px;margin:auto}.md-panel header{display:flex;justify-content:space-between;align-items:center}.md-panel button,.md-panel select{font:inherit;padding:7px 10px;border:1px solid #bbc7d5;border-radius:6px;background:white;cursor:pointer}.md-panel nav,.md-controls{display:flex;flex-wrap:wrap;gap:6px;margin:12px 0}.md-panel .selected{background:#194b80;color:white}.md-warning{padding:12px;background:#fff0d1;border-left:4px solid #b76b00}.md-rule{background:white;border:1px solid #d7e0ec;border-radius:8px;padding:12px;margin:12px 0}.md-scroll{overflow:auto}.md-panel table{border-collapse:collapse;width:100%;min-width:500px}.md-panel th,.md-panel td{border:1px solid #d7e0ec;padding:7px;text-align:left}.md-panel pre{white-space:pre-wrap;overflow-wrap:anywhere}#md-dialog{width:95vw;max-width:1150px;max-height:90vh;padding:0;border:1px solid #b7c7db;border-radius:12px}#md-launch{position:fixed;bottom:14px;right:14px;z-index:9000;background:#173b65;color:white;padding:12px;border:0;border-radius:10px;font-size:14px}dialog::backdrop{background:#0008}@media(max-width:600px){.md-panel{padding:10px;font-size:13px}.md-panel h2{font-size:18px}.md-panel button{padding:8px}#md-dialog{width:98vw;max-height:94vh}#md-launch{bottom:8px;right:8px}}';document.head.appendChild(style);
function init(){panel=document.getElementById('machine-discovery-report');if(panel){panel.className='md-panel';load().catch(e=>panel.textContent=e.message);return;}const dialog=document.createElement('dialog');dialog.id='md-dialog';dialog.innerHTML='<div class="md-panel"></div>';document.body.appendChild(dialog);panel=dialog.firstChild;const btn=document.createElement('button');btn.id='md-launch';btn.textContent='机器发现报告 · 未改评分';btn.onclick=()=>{try{lot=CUR_LOT;}catch(e){}dialog.showModal();if(snapshot){select();recompute();}else{panel.textContent='正在读取研究报告…';load().then(recompute).catch(e=>panel.textContent=e.message);}};document.body.appendChild(btn);setInterval(()=>{if(!dialog.open||busy||source!=='cloud'||!snapshot)return;try{if(CUR_LOT!==lot)return;const digest=JSON.stringify(DR.map(r=>({p:r.p,d:r.d,n:r.n.slice(),t:r.t})));if(digest!==inputDigest)recompute();}catch(e){}},5000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
