(function(){'use strict';let ctx=null,current=null;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=n=>typeof n==='number'?String(n).padStart(2,'0'):n,names={te:'特码',z3:'三中三',lx:'五连肖'};
function attributes(g){if(g.game!=='te')return '';return '<details open><summary>下期属性筛选参考（候选分布，不是命中概率）</summary>'+['生肖','大小','单双','家野','波色','五行','尾数'].map(k=>{let counts={};for(const n of g.pool){let v=ctx.attrs(n)[k];counts[v]=(counts[v]||0)+1;}let v=Object.keys(counts).sort((a,b)=>counts[b]-counts[a]||a.localeCompare(b))[0],ties=Object.keys(counts).filter(x=>counts[x]===counts[v]);const nums=Array.from({length:49},(_,i)=>i+1).filter(n=>ctx.teAllowed(n)&&ctx.attrs(n)[k]===v);return '<p><b>'+k+'：'+ties.map(esc).join(' / ')+(ties.length>1?'（并列，无单一倾向）':'')+'</b>，各占本组'+counts[v]+'/'+g.pool.length+'码。'+(ties.length===1?'若只按“'+esc(v)+'”筛选，剩'+nums.length+'码：'+nums.map(fmt).join(' ')+' <button data-practice-attr="'+esc(g.id)+'" data-kind="'+esc(k)+'" data-value="'+esc(v)+'">应用这个属性范围</button>':'')+'</p>';}).join('')+'</details>';}
function card(g){let title=g.label,body='';if(g.game==='z3')body='<p><b>大范围 '+g.broad.length+'码：</b>'+g.broad.map(fmt).join(' ')+' <button data-practice-sub="'+esc(g.id)+'" data-size="broad">应用大范围</button></p><p><b>重点观察6码：</b>'+g.core.map(fmt).join(' ')+' <button data-practice-sub="'+esc(g.id)+'" data-size="core">应用6码观察池</button></p><p><b>单组三中三备选：</b>'+(g.triples.length?g.triples.map((a,i)=>'第'+(i+1)+'组 ['+a.map(fmt).join(' ')+']').join('；'):'你的组合条件下，没有合格三码组合')+'</p><p>这些三数组从本组候选中分散抽取，没有证据表明某组三码比其他三码更容易中。</p>';
 if(g.game==='lx'){let previous=new Set(ctx.rows.at(-1).n.concat(ctx.rows.at(-1).t).map(ctx.zod));body='<p>与上期相同生肖：'+g.pool.filter(z=>previous.has(z)).join('、')+'；上期未出生肖：'+(g.pool.filter(z=>!previous.has(z)).join('、')||'无')+'。'+g.pool.map(z=>z+'对应 '+Array.from({length:49},(_,i)=>i+1).filter(n=>ctx.zod(n)===z).map(fmt).join('/')).join('；')+'</p>';}
 const baseline=g.game==='lx'?'此处不展示未经独立验证的组合概率。':'均匀随机同宽度基准 '+(100*PracticeEngine.numberBaseline(g.pool.length,g.game)).toFixed(2)+'%'+(g.game==='z3'?'（覆盖至少3个正码）':'（覆盖特码）');
 return '<article class="practice-card"><h4>'+names[g.game]+' · '+esc(title)+'</h4><div class="practice-pool">'+g.pool.map(fmt).join('　')+'</div>'+body+attributes(g)+'<p>'+baseline+'。实验备选，未通过机器独立验证，不宣称优于随机。</p>'+(g.game==='z3'&&g.pool.length<8?'<p>你的限制后不足8码；保持限制，不补入已排号码。</p>':'')+'<button data-practice-apply="'+esc(g.id)+'">应用到'+names[g.game]+'筛选并保存本期</button> <button data-practice-copy="'+esc(g.id)+'">复制本组</button></article>';}
function audit(){const saved=(UP.practice_forecasts||[]).filter(x=>x.lot===CUR_LOT).slice(-9).reverse();return '<details><summary>已保存方案逐期核对（只核对目标期）</summary>'+saved.map(s=>{const draw=ctx.rows.find(r=>r.p===s.targetPeriod),r=draw&&PracticeEngine.score(s,draw,ctx.zod);return '<p>'+s.sourcePeriod+'→<b>'+s.targetPeriod+'期</b> '+names[s.game]+' ['+s.pool.map(fmt).join(' ')+']：'+(r?(r.success?'符合':'未符合')+'，中 '+r.hits.map(fmt).join(' '):'待目标期开奖录入')+'</p>';}).join('')+'<p>这里核对“保存后录入”的目标期，不将它冒充开奖前的前瞻成绩。</p></details>';}
function refresh(){try{if(typeof getPracticeContext!=='function'||typeof UP==='undefined')return;const tabs={plan:['te','z3','lx'],te:['te'],tea:['te'],zm3:['z3'],lx:['lx']};if(!tabs[activeTab])return;ctx=getPracticeContext();if(!ctx)return;current=PracticeEngine.build(ctx);let box=document.getElementById('tabContent');if(!box)return;document.getElementById('practice-panel')?.remove();let groups=current.groups.filter(g=>tabs[activeTab].includes(g.game));box.insertAdjacentHTML('afterbegin','<section id="practice-panel"><h3>本期具体号码与组合 · 10.1009.05</h3><p><b>依据第'+ctx.meta.sourcePeriod+'期 → 预测第'+ctx.meta.targetPeriod+'期</b>。以下是原有策略的不同备选，不是新增已验证规律；不会自动替换你的主评分或选择。相同集合自动合并，不为凑组数复制方案。</p>'+groups.map(card).join('')+(!groups.length?'<p>你的限制下暂无有效组合，请先核对条件。</p>':'')+'<details><summary>本期哪些不能进入候选（你的条件）</summary><p>特码：'+(ctx.blockedTe.map(fmt).join(' ')||'未设')+'</p><p>三中三：'+(ctx.blockedZ3.map(fmt).join(' ')||'未设')+'</p><p>连肖明确排除：'+(ctx.blockedLx.join('、')||'未设')+'</p><p>机器可靠排除：本轮没有通过验证的新增规则，因此不额外列“必杀”。未选入备选的号码或生肖不等于不会开出。</p></details>'+audit()+'</section>');bind();}catch(e){console.error('[practice]',e);}}
function record(g){UP.practice_forecasts=UP.practice_forecasts||[];const id=[CUR_LOT,ctx.meta.sourcePeriod,ctx.meta.targetPeriod,g.id].join('|');if(!UP.practice_forecasts.some(x=>x.recordId===id))UP.practice_forecasts.push({recordId:id,lot:CUR_LOT,sourcePeriod:ctx.meta.sourcePeriod,targetPeriod:ctx.meta.targetPeriod,game:g.game,pool:g.pool.slice(),label:g.label,savedAt:new Date().toISOString(),source:'原有策略实验备选'});}
function apply(g){const fresh=getPracticeContext();if(!fresh||fresh.lot!==ctx.lot||fresh.meta.sourcePeriod!==ctx.meta.sourcePeriod){alert('开奖记录已变化，请重新查看本期方案。');render();return;}
 if(g.game!=='lx'&&g.pool.some(n=>!(g.game==='te'?fresh.teAllowed(n):fresh.z3Allowed(n)))){alert('你的条件已变化，请重新生成。');render();return;}
 if(g.game==='lx'&&!fresh.lx.some(zs=>zs.slice().sort().join(',')===g.pool.slice().sort().join(','))){alert('连肖条件已变化，请重新生成。');render();return;}
 if(g.game==='z3'&&!PracticeEngine.triples(g.pool,fresh.noTogether,fresh.tripleValid).length){alert('当前条件下没有合格的三中三组合，请先核对条件。');return;}
 record(g);if(g.game==='te')UP.te_pick_pool=g.pool.slice();else if(g.game==='z3')UP.zm3_pick_pool=g.pool.slice();else{UP.lx_pick_n_zods=g.pool.slice();UP.lx_pick_k_size=5;}saveData();render();}
function bind(){const el=document.getElementById('practice-panel');el.querySelectorAll('[data-practice-sub]').forEach(b=>b.onclick=()=>{const g=current.groups.find(x=>x.id===b.dataset.practiceSub);if(g)apply({...g,id:g.id+':'+b.dataset.size,pool:g[b.dataset.size].slice()});});el.querySelectorAll('[data-practice-apply]').forEach(b=>b.onclick=()=>{const g=current.groups.find(x=>x.id===b.dataset.practiceApply);if(g)apply(g);});el.querySelectorAll('[data-practice-copy]').forEach(b=>b.onclick=()=>{const g=current.groups.find(x=>x.id===b.dataset.practiceCopy);if(g)navigator.clipboard.writeText(CUR_LOT+' 依据'+ctx.meta.sourcePeriod+'→预测'+ctx.meta.targetPeriod+'期 '+names[g.game]+' '+g.label+'：'+g.pool.map(fmt).join(' ')+'（实验备选）').catch(()=>alert('复制失败，请手动选择号码复制。'));});el.querySelectorAll('[data-practice-attr]').forEach(b=>b.onclick=()=>{const ns=Array.from({length:49},(_,i)=>i+1).filter(n=>ctx.teAllowed(n)&&ctx.attrs(n)[b.dataset.kind]===b.dataset.value);apply({game:'te',id:'attr:'+b.dataset.kind+':'+b.dataset.value+':'+ns.join(','),pool:ns,label:'属性 '+b.dataset.kind+'='+b.dataset.value});});}
const style=document.createElement('style');style.textContent='#practice-panel{border:2px solid #176c52;border-radius:10px;padding:12px;background:#f3faf7;margin:10px 0;font-size:14px;line-height:1.6}.practice-card{background:white;border:1px solid #c9dcd4;border-radius:8px;padding:10px;margin:10px 0}.practice-card h4{margin:0 0 8px}.practice-pool{font-size:20px;font-weight:bold;color:#13563f;overflow-wrap:anywhere}.practice-card button{padding:8px;margin:3px;border-radius:6px;border:1px solid #9dbbae;background:#f1f8f4;cursor:pointer}#practice-panel details{margin:8px 0}#practice-panel p{overflow-wrap:anywhere}@media(max-width:600px){#practice-panel{padding:8px}.practice-pool{font-size:18px}.practice-card button{max-width:100%}}';document.head.appendChild(style);
function init(){const base=window.render;if(typeof base==='function')window.render=function(){const r=base.apply(this,arguments);refresh();return r;};refresh();}
window.PracticeSystem={refresh,show(){activeTab='plan';render();document.getElementById('practice-panel')?.scrollIntoView({block:'start'});}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
