(function(){'use strict';let ctx=null,current=null;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=n=>typeof n==='number'?String(n).padStart(2,'0'):n,names={te:'特码',z3:'三中三',z2:'二中二',tc:'特串',lx:'连肖',pt:'平特一肖'};
function viewContext(independent){const w=typeof winApply==='function'&&activeTab!=='rec'?winApply():false;try{return getPracticeContext(independent);}finally{if(typeof winRelease==='function')winRelease(w);}}
function attributes(g){return g.attribute?'<p><b>本组明确选定 '+esc(g.attribute)+'：'+g.values.map(esc).join('、')+'</b>，按实际特码是否落入此范围核对，不同时给出相反选项。选择来自固定排序的类别平均名次，属于实验决策，不是已验证属性概率。</p>':'';}
function numberNote(n,game){const hit=r=>game==='te'?r.t===n:r.n.includes(n);let om=0;for(let i=ctx.rows.length-1;i>=0&&!hit(ctx.rows[i]);i--)om++;const w=ctx.rows.slice(-30),count=w.filter(hit).length;return fmt(n)+'('+ctx.zod(n)+'，近'+w.length+'次开奖出现'+count+'次，连续'+om+'次未见)';}
function card(g){let title=(g.arm==='fixed'?'系统固定 · ':'按我的条件 · ')+g.label,body='';if(g.game==='z3')body='<p><b>大范围 '+g.broad.length+'码：</b>'+g.broad.map(fmt).join(' ')+' <button data-practice-sub="'+esc(g.id)+'" data-size="broad">应用大范围</button></p><p><b>复式6码：</b>'+g.core.map(fmt).join(' ')+' <button data-practice-sub="'+esc(g.id)+'" data-size="core">应用复式6码</button></p><p><b>主三码（第1组），其余为备选三码：</b>'+(g.triples.length?g.triples.map((a,i)=>'第'+(i+1)+'组 ['+a.map(fmt).join(' ')+']').join('；'):'你的组合条件下，没有合格三码组合')+'</p>'+ g.triples.map((ns,i)=>'<div><b style="color:#176c52">'+(i===0?'主三码':'备选三码')+' 第'+(i+1)+'组：'+ns.map(fmt).join('、')+'</b> '+PracticalActions.buttons(ns,'z3',g.label+'·第'+(i+1)+'组')+'</div>').join('')+'<p>这些三数组从本组候选中分散抽取，没有证据表明某组三码比其他三码更容易中。</p>';
 if(g.game==='te')body='<details><summary>逐码看近期次数与遗漏（只统计特码）</summary>'+g.pool.map(n=>'<p>'+numberNote(n,'te')+'</p>').join('')+'</details>';
 if(g.game==='z3')body+='<details><summary>逐码看生肖、近期次数与遗漏（只统计正码）</summary>'+g.pool.map(n=>'<p>'+numberNote(n,'z3')+'</p>').join('')+'</details>';
 if(g.game==='lx'){let previous=new Set(ctx.rows.at(-1).n.concat(ctx.rows.at(-1).t).map(ctx.zod));body='<p>与上期相同生肖：'+g.pool.filter(z=>previous.has(z)).join('、')+'；上期未出生肖：'+(g.pool.filter(z=>!previous.has(z)).join('、')||'无')+'。'+g.pool.map(z=>{let om=0;for(let i=ctx.rows.length-1;i>=0&&!ctx.rows[i].n.concat(ctx.rows[i].t).some(n=>ctx.zod(n)===z);i--)om++;return z+'（近6次开奖出现'+ctx.rows.slice(-6).filter(r=>r.n.concat(r.t).some(n=>ctx.zod(n)===z)).length+'次，连续'+om+'次未见'+(ctx.zodElement?'，生肖五行'+ctx.zodElement(z):'')+'）对应 '+Array.from({length:49},(_,i)=>i+1).filter(n=>ctx.zod(n)===z).map(fmt).join('/');}).join('；')+'</p>';}
 const baseline=g.game==='lx'?'此处不展示未经独立验证的组合概率':'均匀随机同宽度基准 '+(100*(g.action==='exclude'?1-PracticeEngine.numberBaseline(g.pool.length,g.game):PracticeEngine.numberBaseline(g.pool.length,g.game))).toFixed(2)+'%'+(g.game==='z3'?'（覆盖至少3个正码）':'（本组目标事件）');
 return '<article class="practice-card"><h4>'+(g.game==='z3'?'三中三复式'+g.pool.length+'码':names[g.game])+' · '+esc(title)+'</h4><div class="practice-pool">'+(g.action==='exclude'?'排除：':'候选：')+g.pool.map(fmt).join('　')+'</div>'+body+attributes(g)+PracticalActions.buttons(g.pool,g.game,(g.arm==='fixed'?'系统固定·':'自选条件·')+g.label,g.action)+'<p>'+baseline+'。实验备选，未通过机器独立验证，不宣称优于随机。</p>'+(g.game==='z3'&&g.pool.length<8?'<p>你的限制后不足8码；保持限制，不补入已排号码。</p>':'')+'<button data-practice-apply="'+esc(g.id)+'">应用到'+names[g.game]+'筛选并保存本期</button> <button data-practice-copy="'+esc(g.id)+'">复制到对应筛选并记录</button></article>';}
function audit(){const saved=(UP.practice_forecasts||[]).filter(x=>x.lot===CUR_LOT).slice(-9).reverse();return '<details><summary>已保存方案逐期核对（只核对目标期）</summary>'+saved.map(s=>{const draw=ctx.rows.find(r=>r.p===s.targetPeriod),r=draw&&PredictionReview.score(s,draw,ctx.zod);return '<p>'+s.sourcePeriod+'→<b>'+s.targetPeriod+'期</b> '+(s.arm==='fixed'?'系统固定':'按我的条件')+' '+names[s.game]+' ['+s.pool.map(fmt).join(' ')+']：'+(r?(r.success?'符合':'未符合')+'，中 '+r.hits.map(fmt).join(' '):'待目标期开奖录入')+'</p>';}).join('')+'<p>这里核对“保存后录入”的目标期，不将它冒充开奖前的前瞻成绩。</p></details>';}
function refresh(){try{if(typeof getPracticeContext!=='function'||typeof UP==='undefined')return;const tabs={te:['te'],tea:['te'],zm3:['z3'],lx:['lx','pt']};if(!tabs[activeTab])return;ctx=viewContext();if(!ctx)return;const fixed=viewContext(true);current={groups:[...PracticeEngine.build(fixed).groups.map(g=>({...g,id:'fixed:'+g.id,arm:'fixed'})),...PracticeEngine.build(ctx).groups.map(g=>({...g,id:'filtered:'+g.id,arm:'filtered'}))]};if(typeof winCurOff!=='function'||winCurOff()===0){let changed=false;for(const g of current.groups.filter(g=>g.arm==='fixed')){const old=(UP.practice_forecasts||[]).find(s=>s.lot===CUR_LOT&&s.sourcePeriod===ctx.meta.sourcePeriod&&s.targetPeriod===ctx.meta.targetPeriod&&s.arm==='fixed'&&s.strategy===g.strategy&&s.game===g.game&&s.modelVersion==='10101001');if(old){Object.assign(g,{pool:old.pool.slice(),broad:old.broad||g.broad,core:old.core||g.core,triples:old.triples||g.triples,values:old.values||g.values});}else{record(g);changed=true;}}if(changed)saveData();}let extra=[];for(const g of current.groups.filter(g=>g.game==='lx'&&g.pool.length>=3)){for(const k of [3,4])if(g.pool.length>=k)extra.push({...g,id:g.id+':'+k,strategy:g.strategy+':'+k,label:k+'连肖 · '+g.label,pool:g.pool.slice(0,k)});extra.push({...g,id:g.id+':pt',strategy:g.strategy+':pt',game:'pt',label:'平特一肖 · '+g.label,pool:g.pool.slice(0,1)});}for(const g of extra){if(g.arm==='fixed'&&(!winCurOff||winCurOff()===0))record(g);}current.groups.push(...extra);if(extra.length&&(!winCurOff||winCurOff()===0))saveData();let box=document.getElementById('tabContent');if(!box)return;document.getElementById('practice-panel')?.remove();let groups=current.groups.filter(g=>tabs[activeTab].includes(g.game));for(const arm of ['fixed','filtered']){const ag=current.groups.filter(g=>g.arm===arm&&g.attribute);if(ag.length&&tabs[activeTab].includes('te')){const pool=ag.reduce((ns,g)=>ns.filter(n=>g.pool.includes(n)),Array.from({length:49},(_,i)=>i+1));groups.unshift({id:arm+':intersection',arm,game:'te',strategy:'intersection',label:'明确属性交集（可能为空，不强行凑号）',pool});}}box.insertAdjacentHTML('afterbegin','<section id="practice-panel"><h3>本期具体号码与组合 · 10.1010.16</h3><p><b>依据第'+ctx.meta.sourcePeriod+'期 → 预测第'+ctx.meta.targetPeriod+'期</b>。系统固定组不读取你的筛选条件，首次显示后按期锁定；条件组遵守你的筛选。两组分开复盘。固定组录入前保存不代表开奖前保存，准确率不冒充前瞻。</p>'+groups.map(card).join('')+(!groups.length?'<p>你的限制下暂无有效组合，请先核对条件。</p>':'')+'<details><summary>本期哪些不能进入候选（你的条件）</summary><p>特码：'+(ctx.blockedTe.map(fmt).join(' ')||'未设')+'</p><p>三中三：'+(ctx.blockedZ3.map(fmt).join(' ')||'未设')+'</p><p>连肖明确排除：'+(ctx.blockedLx.join('、')||'未设')+'</p><p>机器可靠排除：本轮没有通过验证的新增规则，因此不额外列“必杀”。未选入备选的号码或生肖不等于不会开出。</p></details>'+audit()+'</section>');bind();}catch(e){console.error('[practice]',e);const box=document.getElementById('tabContent');if(box){document.getElementById('practice-panel')?.remove();box.insertAdjacentHTML('afterbegin','<section id="practice-panel"><b>具体方案加载失败</b><p>'+esc(e.message)+'。请保留此信息用于排查。</p></section>');}}}
function record(g){UP.practice_forecasts=UP.practice_forecasts||[];const id=[CUR_LOT,ctx.meta.sourcePeriod,ctx.meta.targetPeriod,'10101001',g.id].join('|');if(!UP.practice_forecasts.some(x=>x.recordId===id))UP.practice_forecasts.push({recordId:id,lot:CUR_LOT,sourcePeriod:ctx.meta.sourcePeriod,targetPeriod:ctx.meta.targetPeriod,game:g.game,action:g.action||'track',arm:g.arm||'filtered',strategy:g.strategy||g.id,modelVersion:'10101001',pool:g.pool.slice(),broad:g.broad,core:g.core,triples:g.triples,values:g.values,label:g.label,savedAt:new Date().toISOString(),source:'原有策略实验备选'});}
function apply(g){if(typeof winCurOff==='function'&&winCurOff()>0){alert('历史回看只能核对，回到当前轮次后才能应用方案。');return;}const fresh=viewContext();if(!fresh||fresh.lot!==ctx.lot||fresh.meta.sourcePeriod!==ctx.meta.sourcePeriod){alert('开奖记录已变化，请重新查看本期方案。');render();return;}
 if(!['lx','pt'].includes(g.game)&&g.pool.some(n=>!(g.game==='te'?fresh.teAllowed(n):fresh.z3Allowed(n)))){alert('你的条件已变化，请重新生成。');render();return;}
 if(g.game==='lx'&&!fresh.lx.some(zs=>g.pool.every(z=>zs.includes(z)))){alert('连肖条件已变化，请重新生成。');render();return;}
 if(g.game==='z3'&&!PracticeEngine.triples(g.pool,fresh.noTogether,fresh.tripleValid).length){alert('当前条件下没有合格的三中三组合，请先核对条件。');return;}
 record(g);if(g.game==='te'&&g.action==='exclude')UP.te_excl_nums=[...new Set((UP.te_excl_nums||[]).concat(g.pool))];else if(g.game==='te')UP.te_pick_pool=g.pool.slice();else if(g.game==='z3')UP.zm3_pick_pool=g.pool.slice();else if(g.game==='pt'){UP.pt_force_zods=g.pool.slice();}else{UP.lx_pick_n_zods=g.pool.slice();UP.lx_pick_k_size=g.pool.length;}saveData();render();showClickFeedback('✅ 已应用并保存本期方案（'+g.pool.length+'项）');}
function bind(){const el=document.getElementById('practice-panel');el.querySelectorAll('[data-practice-sub]').forEach(b=>b.onclick=()=>{const g=current.groups.find(x=>x.id===b.dataset.practiceSub);if(g)apply({...g,id:g.id+':'+b.dataset.size,pool:g[b.dataset.size].slice()});});el.querySelectorAll('[data-practice-apply]').forEach(b=>b.onclick=()=>{const g=current.groups.find(x=>x.id===b.dataset.practiceApply);if(g)apply(g);});el.querySelectorAll('[data-practice-copy]').forEach(b=>b.onclick=()=>{const g=current.groups.find(x=>x.id===b.dataset.practiceCopy);if(g){apply(g);return;}if(g)navigator.clipboard.writeText(PredictionReview.format(CUR_LOT,g.game,g.pool,g.action)).then(()=>showClickFeedback('✅ 本组已复制并保存')).catch(()=>showClickFeedback('❌ 复制失败，请手动选择号码复制'));});el.querySelectorAll('[data-practice-attr]').forEach(b=>b.onclick=()=>{const ns=Array.from({length:49},(_,i)=>i+1).filter(n=>ctx.teAllowed(n)&&ctx.attrs(n)[b.dataset.kind]===b.dataset.value);apply({game:'te',id:'attr:'+b.dataset.kind+':'+b.dataset.value+':'+ns.join(','),pool:ns,label:'属性 '+b.dataset.kind+'='+b.dataset.value});});}
const style=document.createElement('style');style.textContent='#practice-panel{border:2px solid #176c52;border-radius:10px;padding:12px;background:#f3faf7;margin:10px 0;font-size:14px;line-height:1.6}.practice-card{background:white;border:1px solid #c9dcd4;border-radius:8px;padding:10px;margin:10px 0}.practice-card h4{margin:0 0 8px}.practice-pool{font-size:20px;font-weight:bold;color:#13563f;overflow-wrap:anywhere}.practice-card button{padding:8px;margin:3px;border-radius:6px;border:1px solid #9dbbae;background:#f1f8f4;cursor:pointer}#practice-panel details{margin:8px 0}#practice-panel p{overflow-wrap:anywhere}@media(max-width:600px){#practice-panel{padding:8px}.practice-pool{font-size:18px}.practice-card button{max-width:100%}}';document.head.appendChild(style);
function init(){const base=window.render;if(typeof base==='function')window.render=function(){const r=base.apply(this,arguments);refresh();return r;};refresh();}
window.PracticeSystem={refresh,show(){activeTab='plan';render();document.getElementById('practice-panel')?.scrollIntoView({block:'start'});}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
