(function(){'use strict';let parsed=[],lastDigest='',busy=false;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pct=x=>(100*x).toFixed(1)+'%';
function state(){UP.referenceRules=UP.referenceRules||[];return UP.referenceRules;}
function maps(){return {ZM,WX,WV};}function actualTarget(){return Math.max(...DR.map(r=>r.p))+1;}
function claims(){return state().filter(c=>c.lot===CUR_LOT);}
function summarize(){return ReferenceRules.audit(claims(),DR,maps());}
function panel(){const list=claims(),a=summarize();const rows=a.summaries.map(x=>'<tr><td>'+esc(x.id)+'</td><td>'+x.h+'/'+x.n+'</td><td>'+pct(x.rate)+'</td><td>'+pct(x.baseline)+'</td><td>'+x.pp.toFixed(1)+'百分点</td><td>'+x.status+'</td></tr>').join('');return '<section id="reference-system-panel" style="border:2px solid #385a85;border-radius:9px;padding:10px;margin:10px 0;background:#f6faff"><h3>规律实践 → 实际筛选与逐期核对 · 10.1009.03</h3><p>当前实际记录第'+(actualTarget()-1)+'期；只允许应用到预测第'+actualTarget()+'期。特码杀肖仅排特码号码，不会自动排除连肖平肖。</p><details><summary>录入网站参考（杀肖/尾/头/波色/五行）</summary><p>来源网址：<input id="ref-url" style="width:95%" value="http://49018899.com"></p><label>目标期号 <input id="ref-period" type="number" value="'+actualTarget()+'" style="width:90px"></label> <label>目标开奖日期 <input id="ref-date" type="date"></label><p>用途 <select id="ref-game"><option value="te">特码</option><option value="z3">正码（三中三）</option><option value="lx">连肖（7码生肖）</option></select></p><textarea id="ref-text" rows="6" style="width:100%;box-sizing:border-box" placeholder="逐行粘贴，例如：&#10;特码杀肖：牛 狗&#10;杀尾：3 8&#10;杀头：4&#10;杀波：红&#10;推荐五行：金 水"></textarea><button type="button" data-ref="parse">提取并预览</button><div id="ref-preview"></div><p>开奖前保存才进入前瞻准确率。开奖后补贴的旧资料仅作回顾，不计真实推荐成绩。</p><button type="button" data-ref="save">保存为本期实验参考</button></details><div style="overflow-x:auto"><table style="min-width:550px;width:100%"><tr><th>同一定义参考</th><th>成功/样本</th><th>成功率</th><th>随机排除基准</th><th>提升</th><th>状态</th></tr>'+rows+'</table></div><p>前瞻已核对'+a.valid.length+'条，事后资料'+a.retrospective.length+'条。杀4码成功率的基准为45/49≈91.8%，不能将普通高排除率误当作优势。</p><details open><summary>本期可应用的参考</summary>'+list.filter(c=>c.period===actualTarget()).map(c=>{const ns=ReferenceRules.pool(c,maps());return '<div style="padding:8px;border-top:1px solid #ccd"><b>'+esc(c.game+' '+(c.action==='exclude'?'排除':'追踪')+' '+c.kind+' '+c.values.join('、'))+'</b><p>对应'+ns.length+'码：'+ns.map(n=>String(n).padStart(2,'0')).join(' ')+'</p><button data-apply-ref="'+esc(c.id)+'">实验应用到'+(c.game==='te'?'特码':c.game==='z3'?'三中三':'连肖')+'筛选</button> <button data-undo-ref="'+esc(c.id)+'">撤销本条新增条件</button><small> '+(c.applied?'已应用':'未应用')+' · 未验证，不自动加权</small></div>';}).join('')+'</details><details><summary>最近逐期核对（含失败）</summary>'+a.valid.concat(a.retrospective).slice(-30).reverse().map(c=>'<p>第'+c.period+'期 '+esc(c.raw)+' → '+(c.result.success?'成功':'失败')+'；基准'+pct(c.result.baseline)+'；'+(ReferenceRules.eligible(c)?'开奖前保存':'事后资料，不计前瞻')+'</p>').join('')+'</details><p id="reference-sync-status">自动次日录入：来源接口尚未读取成功，未启用；不会伪装成已运行。</p></section>';}
function expire(){let changed=false;for(const c of claims()){if(c.applied&&c.period!==actualTarget()){release(c);changed=true;}}if(changed)saveData();return changed;}
function release(c){const {key,added}=c.applied;UP[key]=(UP[key]||[]).filter(x=>!added.includes(x));delete c.applied;}
function refresh(){try{if(typeof UP==='undefined'||typeof DR==='undefined'||!DR.length)return;if(expire()){render();return;}const box=document.getElementById('tabContent');if(!box||!['te','tea','zm3','lx','plan','rev','rec'].includes(activeTab))return;let old=document.getElementById('reference-system-panel');if(old)old.remove();box.insertAdjacentHTML('afterbegin',panel());bind();}catch(e){console.error('[reference-system]',e);}}
function bind(){const box=document.getElementById('reference-system-panel');box.querySelector('[data-ref="parse"]').onclick=()=>{const p=ReferenceRules.parse(box.querySelector('#ref-text').value);parsed=p.rules;box.querySelector('#ref-preview').textContent=parsed.map(c=>c.action+' '+c.kind+' '+c.values.join('、')+' → '+ReferenceRules.pool(c,maps()).join(',')).concat(p.warnings).join('\n');};box.querySelector('[data-ref="save"]').onclick=()=>{const text=box.querySelector('#ref-text').value,p=ReferenceRules.parse(text),period=+box.querySelector('#ref-period').value,date=box.querySelector('#ref-date').value,game=box.querySelector('#ref-game').value,url=box.querySelector('#ref-url').value;if(period!==actualTarget()||!date){alert('请核对目标期号，填写真实目标开奖日期。');return;}if(!p.rules.length){alert('未提取到有效参考，请逐行使用“杀肖：牛狗”等格式。');return;}for(const rule of p.rules){const nums=ReferenceRules.pool(rule,maps());if(!nums.length||nums.length===49)continue;const id=[CUR_LOT,period,game,rule.kind,rule.action,rule.values.slice().sort().join(',')].join(':');if(state().some(c=>c.id===id))continue;state().push({...rule,id,lot:CUR_LOT,period,targetDate:date,game,url,capturedAt:new Date().toISOString(),source:'网站参考（用户核对录入）'});}saveData();refresh();};box.querySelectorAll('[data-apply-ref]').forEach(b=>b.onclick=()=>apply(b.dataset.applyRef));box.querySelectorAll('[data-undo-ref]').forEach(b=>b.onclick=()=>undo(b.dataset.undoRef));}
function keys(c){return c.game==='te'?[c.action==='exclude'?'te_excl_nums':'te_pick_pool']:c.game==='z3'?[c.action==='exclude'?'zm3_excl_nums':'zm3_pick_pool']:[c.action==='exclude'?'lx_excl_zods':'lx_force_zods'];}
function apply(id){const c=state().find(c=>c.id===id);if(!c||c.period!==actualTarget()||c.lot!==CUR_LOT||c.applied)return;let ns=ReferenceRules.pool(c,maps()),key=keys(c)[0];if(c.game==='lx'){if(c.kind!=='生肖'){alert('连肖只能应用明确的生肖条件，号码波色不能直接当作整肖排除。');return;}ns=c.values.slice();}if(c.action==='track'&&c.game!=='lx'){const blocked=new Set(UP[c.game==='te'?'te_excl_nums':'zm3_excl_nums']||[]);ns=ns.filter(n=>!blocked.has(n));}if(state().some(x=>x.lot===CUR_LOT&&x.id!==id&&x.applied?.key===key)){alert('该筛选已有网站参考，请先撤销上一条，避免条件混淆。');return;}if(c.game==='lx'){const opposite=UP[c.action==='exclude'?'lx_force_zods':'lx_excl_zods']||[];if(ns.some(x=>opposite.includes(x))){alert('与已有生肖选择冲突，请先核对自己的条件。');return;}}const existing=UP[key]||[];if(c.action==='track'&&existing.length){alert('已有候选池，请先核对或清空原候选池，避免扩大你的筛选范围。');return;}if(!ns.length){alert('参考号码已被你的排除条件全部过滤。');return;}const added=ns.filter(n=>!existing.includes(n));c.applied={key,added,at:new Date().toISOString()};UP[key]=[...new Set(existing.concat(ns))];saveData();render();refresh();}
function undo(id){const c=state().find(c=>c.id===id);if(!c||!c.applied)return;release(c);saveData();render();refresh();}
function init(){const base=window.render;if(typeof base==='function')window.render=function(){const r=base.apply(this,arguments);refresh();return r;};refresh();setInterval(()=>{if(busy)return;try{const digest=JSON.stringify([CUR_LOT,activeTab,DR,state()]);if(lastDigest!==digest){lastDigest=digest;refresh();}}catch(e){}},5000);}
function applyMachine(rule,ruleLot,sourcePeriod){
 if(ruleLot!==CUR_LOT||sourcePeriod!==actualTarget()-1){alert('请先用当前彩种的最新记录重新计算。');return;}
 const f=rule.forward,dir=rule.type==='排除规律'?-1:1;
 if(rule.status!=='已验证规律'||!rule.active||!f||f.n<30||f.p>0.0001||dir*f.pp<=0||dir*f.randomPP<=0){alert('尚未通过独立验证及未来期验证，不进入正式筛选。');return;}
 const ns=rule.candidatePool||[];
 if(!ns.length||ns.length>=(rule.game==='lx'?12:49)||(dir<0&&rule.game!=='te')){alert('此结构关系不能安全转换成号码或整肖排除。');return;}
 if(rule.game==='lx'&&ns.length>6){alert('此集合超过六肖，不能直接当作连肖强选条件。');return;}
 const id=['machine',CUR_LOT,actualTarget(),rule.id].join(':');
 if(!state().some(c=>c.id===id))state().push({id,lot:CUR_LOT,period:actualTarget(),game:rule.game,kind:rule.game==='lx'?'生肖':'号码',values:ns.slice(),action:dir<0?'exclude':'track',source:rule.source,raw:rule.label,ruleId:rule.id,capturedAt:new Date().toISOString(),validation:{train:rule.train,holdout:rule.validation,forward:f}});
 apply(id);
}
window.ReferenceSystem={refresh,apply,undo,applyMachine};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
