/* Source tips are data, never executable instructions. Pure parser/audit shared with tests. */
(function(root){'use strict';
const C=(n,k)=>{if(k<0||k>n)return 0;let v=1;for(let i=1;i<=k;i++)v=v*(n-k+i)/i;return v;};
const uniq=a=>[...new Set(a)];const zods='鼠牛虎兔龙蛇马羊猴鸡狗猪'.split('');
function parse(text){let out=[],warnings=[];for(const raw of String(text).split(/[\n；;]/)){const s=raw.trim();if(!s)continue;if(/上期|开奖结果|已开奖|开奖回顾/.test(s)){warnings.push('跳过历史/开奖说明：'+s);continue;}const action=/杀|排除|不出/.test(s)?'exclude':/推荐|看好|追踪|候选/.test(s)?'track':null;if(!action)continue;let kind,values=[];if(/生肖|杀肖|排肖/.test(s)){kind='生肖';values=uniq(s.split(/[:：]/).slice(1).join(':').split('').filter(c=>zods.includes(c)));}else if(/尾/.test(s)){kind='尾数';values=uniq((s.split(/[:：]/).slice(1).join(':').match(/\d+/g)||[]).map(Number));}else if(/头/.test(s)){kind='头数';values=uniq((s.split(/[:：]/).slice(1).join(':').match(/\d+/g)||[]).map(Number));}else if(/波/.test(s)){kind='波色';values=uniq((s.split(/[:：]/).slice(1).join(':').match(/[红蓝绿]/g)||[]));}else if(/五行/.test(s)){kind='五行';values=uniq((s.split(/[:：]/).slice(1).join(':').match(/[金木水火土]/g)||[]));}else if(/号码|杀码|排码/.test(s)){kind='号码';values=uniq((s.split(/[:：]/).slice(1).join(':').match(/\d+/g)||[]).map(Number));}else{warnings.push('未识别的属性说明：'+s);continue;}
if(!values.length||values.some(v=>(kind==='尾数'&&(v<0||v>9))||(kind==='头数'&&(v<0||v>4))||(kind==='号码'&&(v<1||v>49)))){warnings.push('需核对，未导入：'+s);continue;}out.push({kind,values,action,raw:s});}return {rules:out,warnings};}
function pool(rule,maps){const A=Array.from({length:49},(_,i)=>i+1);return A.filter(n=>rule.kind==='号码'?rule.values.includes(n):rule.kind==='尾数'?rule.values.includes(n%10):rule.kind==='头数'?rule.values.includes(Math.floor(n/10)):rule.values.some(v=>(maps[rule.kind==='生肖'?'ZM':rule.kind==='五行'?'WX':'WV'][v]||[]).includes(n)));}
function evaluate(claim,draw,maps){const ns=pool(claim,maps),game=claim.game||'te',actual=game==='te'?[draw.t]:game==='z3'?draw.n:draw.n.concat(draw.t),hits=actual.filter(n=>ns.includes(n));let p=game==='te'?ns.length/49:1-C(49-ns.length,actual.length)/C(49,actual.length);if(claim.action==='exclude')p=1-p;return {success:claim.action==='exclude'?hits.length===0:hits.length>0,baseline:p,hitNumbers:hits,removed:ns.length};}
function eligible(claim){if(!claim.targetDate||!claim.capturedAt)return false;const deadline=Date.parse(claim.targetDate+'T21:35:00+08:00');return Number.isFinite(deadline)&&Date.parse(claim.capturedAt)<deadline;}
function audit(claims,rows,maps){let valid=[],retrospective=[];for(const c of claims){const r=rows.find(x=>x.p===c.period);if(!r)continue;const item={...c,result:evaluate(c,r,maps)};(eligible(c)?valid:retrospective).push(item);}const series=new Map();for(const c of valid){const key=[c.game,c.kind,c.action,c.values.slice().sort().join(',')].join(':');if(!series.has(key))series.set(key,[]);series.get(key).push(c);}const summaries=[...series].map(([id,items])=>{const n=items.length,h=items.filter(c=>c.result.success).length,p=items.reduce((s,c)=>s+c.result.baseline,0)/n;return {id,n,h,rate:h/n,baseline:p,pp:100*(h/n-p),status:n<30?'样本不足，实验参考':'待独立验证，不自动进入评分'};});return {valid,retrospective,summaries};}
root.ReferenceRules={parse,pool,evaluate,eligible,audit};if(typeof module!=='undefined')module.exports=root.ReferenceRules;
})(typeof self!=='undefined'?self:globalThis);
