(function(root){'use strict';
const C=(n,k)=>{let x=1;for(let i=1;i<=k;i++)x*= (n-k+i)/i;return k>n?0:x;};
function run(rows,attrs,fisher){
 const all=Array.from({length:49},(_,i)=>i+1),split=Math.floor(rows.length*.7),rules=[];
 function stats(events,a,b){let n=0,h=0,e=0,rn=0,rh=0;for(let i=Math.max(6,a);i<b;i++){const x=events[i];if(!x)continue;if(x.on){n++;h+=x.hit;e+=x.base;}else{rn++;rh+=x.hit;}}const rate=n?h/n:null,base=n?e/n:null;return {n,h,rate,base,pp:n?100*(rate-base):null,p:n&&rn?fisher(h,n-h,rh,rn-rh):1,unconditional:n+rn?(h+rh)/(n+rn):null,comparison:rn?rh/rn:null};}
 function add(label,target,value,kind,events,current,nums){const train=stats(events,0,split),validation=stats(events,split,rows.length),full=stats(events,0,rows.length),recent={};[30,50,100].forEach(n=>recent[n]=stats(events,Math.max(0,rows.length-n),rows.length));const blocks=[];for(let a=split;a<rows.length;a+=20)blocks.push(stats(events,a,Math.min(rows.length,a+20)));rules.push({label,target,value,kind,train,validation,full,recent,blocks,current,nums});}
 function fdr(key){const sorted=rules.slice().sort((a,b)=>a[key].p-b[key].p);let q=1;for(let i=sorted.length-1;i>=0;i--){q=Math.min(q,sorted[i][key].p*sorted.length/(i+1));sorted[i][key].q=q;}}
 for(const k of ['波色','五行','生肖','尾数','头数']){const vals=[...new Set(all.map(n=>String(attrs(n)[k])))];for(const value of vals){const nums=all.filter(n=>String(attrs(n)[k])===value),base=nums.length/49;for(const kind of ['热值','冷值'])for(const target of ['te','z3']){let events=[],current=false;for(let i=6;i<=rows.length;i++){const counts=Object.fromEntries(vals.map(v=>[v,0]));rows.slice(i-6,i).forEach(r=>r.n.concat(r.t).forEach(n=>counts[String(attrs(n)[k])]++));const limit=(kind==='热值'?Math.max:Math.min)(...Object.values(counts)),on=counts[value]===limit;if(i===rows.length){current=on;break;}if(rows[i].p!==rows[i-1].p+1)continue;events[i]={on,hit:target==='te'?+(String(attrs(rows[i].t)[k])===value):+rows[i].n.some(n=>String(attrs(n)[k])===value),base:target==='te'?base:1-C(49-nums.length,6)/C(49,6)};}add('前6期42码中'+k+'「'+value+'」为'+kind,target,value,'42码'+k,events,current,nums);}}}
 // Count DISTINCT missing numbers, not occurrence counts: six draws contain 42 balls but repeats do not consume new numbers.
 for(const k of ['波色','五行','生肖','尾数','头数'])for(const value of [...new Set(all.map(n=>String(attrs(n)[k])))]){const nums=all.filter(n=>String(attrs(n)[k])===value);for(let missing=0;missing<=nums.length;missing++)for(const target of ['te','z3']){const events=[];let current=false;for(let i=6;i<=rows.length;i++){const seen=new Set(rows.slice(i-6,i).flatMap(r=>r.n.concat(r.t))),on=nums.filter(n=>!seen.has(n)).length===missing;if(i===rows.length){current=on;break;}if(rows[i].p!==rows[i-1].p+1)continue;events[i]={on,hit:target==='te'?+nums.includes(rows[i].t):+rows[i].n.some(n=>nums.includes(n)),base:target==='te'?nums.length/49:1-C(49-nums.length,6)/C(49,6)};}add('【'+value+'】近6期42码未出'+missing+'个不同号码 → 下期'+(target==='te'?'特码属于该属性':'正码至少含该属性'),target,value,'未出数量·'+k,events,current,nums);}}
 const zs=[...new Set(all.map(n=>attrs(n).生肖))];for(const z of zs){const nums=all.filter(n=>attrs(n).生肖===z),presence=rows.map(r=>r.n.concat(r.t).some(n=>attrs(n).生肖===z));for(const mode of ['连续1期','连续2期','连续3期以上','断开1期','断开2期','断开3期以上']){let events=[],current=false;for(let i=6;i<=rows.length;i++){let onState=mode.startsWith('连续'),streak=0;for(let j=i-1;j>=0&&presence[j]===onState;j--)streak++;const bucket=mode.includes('以上')?streak>=3:streak===Number(mode.match(/\d/)[0]);if(i===rows.length){current=bucket;break;}if(rows[i].p!==rows[i-1].p+1)continue;events[i]={on:bucket,hit:+presence[i],base:1-C(49-nums.length,7)/C(49,7)};}add(z+'生肖'+mode+' → 下期7码仍含'+z,'lx',z,'生肖连续/断开',events,current,nums);}}
 for(const n of all)for(const target of ['te','z3']){const events=[];let current=false;for(let i=6;i<=rows.length;i++){const count=rows.slice(i-6,i).reduce((s,r)=>s+r.n.concat(r.t).filter(x=>x===n).length,0),on=count>=2;if(i===rows.length){current=on;break;}if(rows[i].p!==rows[i-1].p+1)continue;events[i]={on,hit:target==='te'?+(rows[i].t===n):+rows[i].n.includes(n),base:target==='te'?1/49:6/49};}add('号码'+String(n).padStart(2,'0')+'近6期七码出现≥2次 → 下期'+(target==='te'?'特':'正'),target,String(n),'重复号次数',events,current,[n]);}
 for(const value of [...new Set(all.map(n=>attrs(n).五行))])for(const target of ['te','z3']){const nums=all.filter(n=>attrs(n).五行===value),events=[];let current=false;for(let i=6;i<=rows.length;i++){const on=rows[i-1].n.filter(n=>nums.includes(n)).length>=3;if(i===rows.length){current=on;break;}if(rows[i].p!==rows[i-1].p+1)continue;events[i]={on,hit:target==='te'?+nums.includes(rows[i].t):+rows[i].n.some(n=>nums.includes(n)),base:target==='te'?nums.length/49:1-C(49-nums.length,6)/C(49,6)};}add('上期正码'+value+'行≥3个 → 下期是否继续',target,value,'五行密集',events,current,nums);}
 for(const key of ['大小','单双','合数单双','家野','波色','五行'])for(const value of [...new Set(all.map(n=>attrs(n)[key]))].filter(v=>v!==undefined))for(const minimum of [3,5,7]){const nums=all.filter(n=>attrs(n)[key]===value),events=[];let current=false;for(let i=6;i<=rows.length;i++){let streak=0;for(let j=i-1;j>=0&&attrs(rows[j].t)[key]===value;j--)streak++;const on=streak>=minimum;if(i===rows.length){current=on;break;}if(rows[i].p!==rows[i-1].p+1)continue;events[i]={on,hit:+nums.includes(rows[i].t),base:nums.length/49};}add('特码'+key+'「'+value+'」连开≥'+minimum+'期 → 是否延续','te',value,'特码连开',events,current,nums);}
 fdr('train');fdr('validation');for(const r of rules){const t=r.train,v=r.validation,sign=Math.sign(t.pp||0),blocks=r.blocks.filter(b=>b.n>=5);r.direction=sign<0?'排除观察':'追踪观察';r.eligible=t.n>=30&&v.n>=20&&t.q<=.05&&v.q<=.05&&sign===Math.sign(v.pp||0)&&Math.sign((v.rate||0)-(v.comparison||0))===sign&&blocks.length>=2&&blocks.every(b=>Math.sign(b.pp||0)===sign);r.status=r.eligible?'独立验证通过·待前瞻':t.n<30||v.n<20?'样本不足':Math.sign(v.pp||0)!==sign?'验证反向·淘汰':t.q>.05||v.q>.05?'多重检验未通过':'滚动表现不稳定';r.weight=r.eligible?Math.max(-1,Math.min(1,Math.log((v.h+20*v.base)/(v.n+20)/v.base))):0;}
 return {rows:rows.length,split,tests:rules.length,rules};
}
root.TransitionAudit={run};if(typeof module!=='undefined')module.exports=root.TransitionAudit;
})(typeof self!=='undefined'?self:globalThis);
